-- Comprehensive Seed data based on mock files

-- Clear existing data
TRUNCATE public.profiles RESTART IDENTITY CASCADE;
TRUNCATE public.groups RESTART IDENTITY CASCADE;
TRUNCATE public.group_reports RESTART IDENTITY CASCADE;
TRUNCATE public.meetup_events RESTART IDENTITY CASCADE;
TRUNCATE public.social_posts RESTART IDENTITY CASCADE;
TRUNCATE public.discord_info RESTART IDENTITY CASCADE;

-- 1. Profiles (from mockUsers.ts)
INSERT INTO public.profiles (id, name, email, role, status, "joinedDate")
VALUES 
('1', 'Jane Doe', 'jane@example.com', 'user', 'active', '2023-01-15'),
('2', 'Admin User', 'admin@example.com', 'admin', 'active', '2022-11-01'),
('3', 'John Smith', 'john@example.com', 'user', 'active', '2023-03-20'),
('4', 'Sarah Wilson', 'sarah@example.com', 'user', 'banned', '2023-02-10'),
('5', 'Mike Johnson', 'mike@example.com', 'user', 'active', '2023-05-05');

-- 2. Groups (from mockGroups.ts)
INSERT INTO public.groups (id, name, catchline, "coverImage", "memberCount", "meetingFrequency", description, privacy, location, "primaryVenue", tags, "groupType", "groupSize", "experienceLevel", "isClaimed", "isVerified", "isActive", organizer, "contactMethods", "meetupDetails", status)
VALUES 
('1', 'Brooklyn Strategy Guild', 'Mastering heavy Euros and complex strategy games together.', 'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=800&h=400&fit=crop', 87, 'Weekly', 'A passionate community of strategy game enthusiasts meeting every Thursday evening. We focus on Euro-style games and competitive play.', 'Public', '{"city": "Brooklyn", "state": "NY", "zipCode": "11211", "coordinates": {"lat": 40.7128, "lng": -73.9610}}'::jsonb, 'The Brooklyn Strategist', ARRAY['Strategy', 'Heavy', 'Competitive', 'Euro Games'], 'Board Game Group', 'Large', 'Advanced', true, true, true, 'Sarah Martinez', ARRAY['website', 'email', 'meetup', 'discord', 'bgg'], '{"privacy": "Public"}'::jsonb, 'approved'),
('2', 'Austin Party Gamers', 'Weekly laughs, social deduction, and light strategy for everyone.', 'https://images.unsplash.com/photo-1566995541237-b2c752a74e7d?w=800&h=400&fit=crop', 156, 'Bi-weekly', 'Social gaming group focused on fun and laughter. Perfect for newcomers and casual players who love party games and social deduction.', 'Public', '{"city": "Austin", "state": "TX", "zipCode": "73301", "coordinates": {"lat": 30.2672, "lng": -97.7431}}'::jsonb, 'Vigilante Gastropub & Games', ARRAY['Party', 'Social', 'Casual', 'Light'], 'Social Group', 'Large', 'Beginner Friendly', true, true, true, 'Jane Doe', ARRAY['facebook', 'whatsapp', 'instagram'], null, 'approved'),
('3', 'Seattle RPG Alliance', 'Explore fantastic worlds in our dedicated D&D and Pathfinder campaigns.', 'https://images.unsplash.com/photo-1612404776058-c3d6836e31df?w=800&h=400&fit=crop', 24, 'Weekly', 'Dedicated roleplaying community running multiple campaigns. From D&D to Pathfinder, we explore fantastic worlds together.', 'Private', '{"city": "Seattle", "state": "WA", "zipCode": "98101", "coordinates": {"lat": 47.6062, "lng": -122.3321}}'::jsonb, 'Mox Boarding House', ARRAY['RPG', 'D&D', 'Cooperative'], 'DND Group', 'Medium', 'All Levels', false, false, true, 'Alex Chen', ARRAY['discord', 'email', 'warhorn'], null, 'approved'),
('4', 'Denver Card Collective', NULL, 'https://images.unsplash.com/photo-1611371805429-8b5c1b2c34ba?w=800&h=400&fit=crop', 42, 'Weekly', 'Card game enthusiasts unite! From deck-builders to living card games, we play it all. Weekly tournaments and friendly matches.', 'Public', '{"city": "Denver", "state": "CO", "zipCode": "80202", "coordinates": {"lat": 39.7392, "lng": -104.9903}}'::jsonb, 'Wizard''s Chest', ARRAY['Card Games', 'Competitive', 'Medium'], 'Card Game Group', 'Medium', 'Intermediate', true, true, true, 'Jessica Park', ARRAY['website', 'discord', 'meetup', 'twitter'], '{"privacy": "Private"}'::jsonb, 'approved'),
('5', 'Portland Casual Crew', 'No pressure, just good vibes and great games.', 'https://images.unsplash.com/photo-1632501641765-e568d1e3e0e6?w=800&h=400&fit=crop', 15, 'Monthly', 'Laid-back monthly gatherings for board game lovers. No pressure, just good vibes and great games. All skill levels welcome!', 'Public', '{"city": "Portland", "state": "OR", "zipCode": "97205", "coordinates": {"lat": 45.5152, "lng": -122.6784}}'::jsonb, NULL, ARRAY['Party', 'Casual', 'Light'], 'Social Group', 'Small', 'Beginner Friendly', false, false, false, 'Chris Thompson', ARRAY['facebook', 'email'], null, 'approved'),
('6', 'Chicago Competitive League', 'Prove your mastery in ranked tournaments.', 'https://images.unsplash.com/photo-1606167668584-78701c57f13d?w=800&h=400&fit=crop', 203, 'Weekly', 'Serious gamers seeking challenging competition. Regular tournaments, ranked play, and skilled opponents. Prove your mastery!', 'Public', '{"city": "Chicago", "state": "IL", "zipCode": "60601", "coordinates": {"lat": 41.8781, "lng": -87.6298}}'::jsonb, 'Dice Dojo', ARRAY['Strategy', 'Competitive', 'Heavy'], 'Board Game Group', 'Large', 'Advanced', true, true, true, 'David Williams', ARRAY['website', 'discord', 'email', 'aftergame'], null, 'approved'),
('7', 'Boston Board Game Beginners', 'We teach games and build confidence.', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=400&fit=crop', 68, 'Bi-weekly', 'New to board gaming? This is your home! We teach games, build confidence, and create a welcoming space for learning.', 'Public', '{"city": "Boston", "state": "MA", "zipCode": "02108", "coordinates": {"lat": 42.3601, "lng": -71.0589}}'::jsonb, 'Knight Moves Cafe', ARRAY['Party', 'Casual', 'Light', 'Beginner Friendly'], 'Board Game Group', 'Medium', 'Beginner Friendly', false, false, true, 'Emily Rodriguez', ARRAY['meetup', 'email', 'instagram'], null, 'approved'),
('8', 'San Francisco Dice Masters', NULL, 'https://images.unsplash.com/photo-1640340434855-6084b1f4901c?w=800&h=400&fit=crop', 31, 'Weekly', 'Dice games, miniatures, and tactical combat. For players who love probability, positioning, and pushing their luck.', 'Private', '{"city": "San Francisco", "state": "CA", "zipCode": "94103", "coordinates": {"lat": 37.7749, "lng": -122.4194}}'::jsonb, NULL, ARRAY['Miniatures', 'Strategy', 'Medium'], 'Board Game Group', 'Medium', 'Intermediate', true, true, true, 'Ryan Lee', ARRAY['website', 'discord', 'telegram'], null, 'approved'),
('9', 'Nashville Social Gamers', 'Where gaming meets community!', 'https://images.unsplash.com/photo-1566576721346-d4a3b4eaeb55?w=800&h=400&fit=crop', 94, 'Bi-weekly', 'Where gaming meets community! Bi-weekly meetups with a focus on building friendships through play. Everyone is family here.', 'Public', '{"city": "Nashville", "state": "TN", "zipCode": "37203", "coordinates": {"lat": 36.1627, "lng": -86.7816}}'::jsonb, 'Game Point Cafe', ARRAY['Party', 'Social', 'Casual'], 'Social Group', 'Large', 'All Levels', true, true, true, 'Amanda Davis', ARRAY['facebook', 'whatsapp', 'website', 'meetup'], null, 'approved'),
('10', 'Miami Miniatures & More', NULL, 'https://images.unsplash.com/photo-1601850494422-3cf14624b0b3?w=800&h=400&fit=crop', 12, 'Monthly', 'Small but dedicated group focused on miniature wargaming and painting. Share techniques, battle strategies, and showcase your armies.', 'Private', '{"city": "Miami", "state": "FL", "zipCode": "33101", "coordinates": {"lat": 25.7617, "lng": -80.1918}}'::jsonb, NULL, ARRAY['Miniatures', 'Strategy', 'Heavy'], 'Board Game Group', 'Small', 'All Levels', false, false, false, 'Carlos Garcia', ARRAY['discord', 'email', 'instagram'], null, 'approved'),
('11', 'Phoenix Fantasy Fans', NULL, 'https://images.unsplash.com/photo-1595429159057-c4ba8e45304d?w=800&h=400&fit=crop', 51, 'Weekly', 'Immerse yourself in fantasy-themed board games and RPGs. From epic quests to dungeon crawls, adventure awaits!', 'Public', '{"city": "Phoenix", "state": "AZ", "zipCode": "85001", "coordinates": {"lat": 33.4484, "lng": -112.0740}}'::jsonb, NULL, ARRAY['RPG', 'Strategy', 'Medium', 'Cooperative'], 'RPG Group', 'Medium', 'All Levels', true, true, true, 'Lisa Nguyen', ARRAY['website', 'meetup', 'discord', 'reddit'], null, 'approved'),
('12', 'Minneapolis Monday Night Gaming', 'A Monday night tradition for over 3 years.', 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=800&h=400&fit=crop', 78, 'Weekly', 'Monday night tradition for over 3 years! Consistent group of friendly gamers playing everything from classics to new releases.', 'Public', '{"city": "Minneapolis", "state": "MN", "zipCode": "55401", "coordinates": {"lat": 44.9778, "lng": -93.2650}}'::jsonb, 'Fantasy Flight Games Center', ARRAY['Strategy', 'Card Games', 'Party', 'Medium'], 'Board Game Group', 'Large', 'All Levels', false, false, true, 'Tom Anderson', ARRAY['meetup', 'facebook'], null, 'approved'),
('13', 'Tampa Bay Tabletop', NULL, 'https://images.unsplash.com/photo-1632501641765-e568d1e3e0e6?w=800&h=400&fit=crop', 45, 'Weekly', 'New group forming in the Tampa Bay area! We''re excited to build a community of tabletop enthusiasts. Currently meeting at local game stores.', 'Public', '{"city": "Tampa", "state": "FL", "zipCode": "33602", "coordinates": {"lat": 27.9506, "lng": -82.4572}}'::jsonb, NULL, ARRAY['Strategy', 'Casual', 'Light'], 'Board Game Group', 'Medium', 'All Levels', true, false, true, 'Jennifer Williams', ARRAY['discord', 'facebook', 'email'], null, 'approved'),
('14', 'Silicon Valley Strategy Society', 'Deep strategy for analytical minds.', 'https://images.unsplash.com/photo-1606167668584-78701c57f13d?w=800&h=400&fit=crop', 112, 'Bi-weekly', 'Tech professionals who love deep strategy games. We meet bi-weekly for intense gaming sessions featuring heavy Euro games and economic simulations.', 'Private', '{"city": "San Jose", "state": "CA", "zipCode": "95113", "coordinates": {"lat": 37.3382, "lng": -121.8863}}'::jsonb, 'Game Kastle', ARRAY['Strategy', 'Heavy', 'Competitive', 'Euro Games'], 'Board Game Group', 'Large', 'Advanced', true, true, true, 'Kevin Zhang', ARRAY['website', 'discord', 'email', 'bgg'], null, 'approved'),
('15', 'Atlanta RPG Adventurers', 'Epic adventures await in our weekly D&D sessions!', 'https://images.unsplash.com/photo-1612404776058-c3d6836e31df?w=800&h=400&fit=crop', 34, 'Weekly', 'Multiple D&D campaigns running simultaneously! New group looking to expand our roster of players and dungeon masters.', 'Public', '{"city": "Atlanta", "state": "GA", "zipCode": "30303", "coordinates": {"lat": 33.7490, "lng": -84.3880}}'::jsonb, NULL, ARRAY['RPG', 'D&D', 'Fantasy'], 'DND Group', 'Medium', 'All Levels', true, false, true, 'Marcus Johnson', ARRAY['discord', 'meetup', 'whatsapp'], null, 'approved'),
('16', 'Las Vegas Game Night', NULL, 'https://images.unsplash.com/photo-1566995541237-b2c752a74e7d?w=800&h=400&fit=crop', 89, 'Weekly', 'What happens in Vegas... gets played on our tables! Social gaming group meeting at various casinos and game cafes.', 'Public', '{"city": "Las Vegas", "state": "NV", "zipCode": "89109", "coordinates": {"lat": 36.1699, "lng": -115.1398}}'::jsonb, 'Meepleville Board Game Cafe', ARRAY['Party', 'Social', 'Card Games', 'Light'], 'Social Group', 'Large', 'Beginner Friendly', false, false, false, 'Rachel Kim', ARRAY['meetup', 'facebook', 'twitter'], null, 'approved'),
('17', 'Philadelphia Wargaming Coalition', NULL, 'https://images.unsplash.com/photo-1601850494422-3cf14624b0b3?w=800&h=400&fit=crop', 56, 'Bi-weekly', 'Dedicated to miniature wargaming and historical simulations. Newly organized group seeking verification and new members.', 'Private', '{"city": "Philadelphia", "state": "PA", "zipCode": "19103", "coordinates": {"lat": 39.9526, "lng": -75.1652}}'::jsonb, NULL, ARRAY['Miniatures', 'Strategy', 'Heavy', 'Historical'], 'Board Game Group', 'Medium', 'Intermediate', true, false, true, 'Steven Cooper', ARRAY['website', 'discord', 'email', 'warhorn'], null, 'approved'),
('18', 'Raleigh Board Game Brewers', 'Craft beer and board games - the perfect pairing.', 'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=800&h=400&fit=crop', 67, 'Monthly', 'Games and craft beer! We meet monthly at local breweries to enjoy board games and good company. Family-friendly earlier sessions available.', 'Public', '{"city": "Raleigh", "state": "NC", "zipCode": "27601", "coordinates": {"lat": 35.7796, "lng": -78.6382}}'::jsonb, 'Raleigh Brewing Company', ARRAY['Strategy', 'Party', 'Casual', 'Social', 'Medium'], 'Social Group', 'Medium', 'All Levels', true, true, true, 'Nicole Brown', ARRAY['website', 'meetup', 'facebook', 'email'], null, 'approved'),
('19', 'Dallas Dice & Dragons', NULL, 'https://images.unsplash.com/photo-1595429159057-c4ba8e45304d?w=800&h=400&fit=crop', 28, 'Weekly', 'D&D 5E focused group with experienced DMs running epic campaigns. Currently full but accepting waitlist members.', 'Private', '{"city": "Dallas", "state": "TX", "zipCode": "75201", "coordinates": {"lat": 32.7767, "lng": -96.7970}}'::jsonb, NULL, ARRAY['RPG', 'D&D', 'Fantasy'], 'DND Group', 'Medium', 'Intermediate', true, true, true, 'Brian Mitchell', ARRAY['discord', 'email', 'whatsapp', 'telegram'], null, 'approved'),
('20', 'Sacramento Card Game Club', NULL, 'https://images.unsplash.com/photo-1611371805429-8b5c1b2c34ba?w=800&h=400&fit=crop', 39, 'Bi-weekly', 'From Magic to Pokemon to modern deck-builders, we love all card games! Bi-weekly tournaments and casual play sessions.', 'Public', '{"city": "Sacramento", "state": "CA", "zipCode": "95814", "coordinates": {"lat": 38.5816, "lng": -121.4944}}'::jsonb, 'Big Brother Comics', ARRAY['Card Games', 'Competitive', 'Strategy', 'Medium'], 'Card Game Group', 'Medium', 'All Levels', false, false, true, 'Angela Torres', ARRAY['meetup', 'discord', 'facebook', 'aftergame'], null, 'approved'),
('21', 'Full Experience Public Group A', 'The ultimate board game experience for everyone, everywhere.', 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=800&h=400&fit=crop', 500, 'Weekly', 'We are the gold standard for community gaming. Open to everyone, we play everything from light party games to heavy strategy epics. Join us for our massive weekly meetups, tournaments, charity events, and more. We have a dedicated venue, a huge library, and a welcoming atmosphere.', 'Public', '{"city": "New York", "state": "NY", "zipCode": "10001", "coordinates": {"lat": 40.7128, "lng": -74.0060}}'::jsonb, 'Hex & Company', ARRAY['Strategy', 'Party', 'Social', 'RPG', 'Card Games', 'Miniatures', 'Competitive', 'Cooperative', 'Light', 'Medium', 'Heavy'], 'Board Game Group', 'Large', 'All Levels', true, true, true, 'The Game Master', ARRAY['website', 'discord', 'facebook', 'meetup', 'email', 'whatsapp', 'bgg', 'reddit', 'instagram', 'telegram', 'warhorn', 'twitter', 'aftergame'], '{"privacy": "Public"}'::jsonb, 'approved');

-- 3. Group Reports (from mockReports.ts)
INSERT INTO public.group_reports (id, "groupId", "groupName", reason, description, "reporterEmail", "reporterName", status, timestamp)
VALUES 
('1', '16', 'Las Vegas Game Night', 'Inaccurate Location', 'The venue listed has been closed for 2 months. They now meet at The Dice Tower.', 'user@example.com', NULL, 'pending', NOW() - INTERVAL '1 day'),
('2', '2', 'Austin Party Gamers', 'Spam', 'This group seems to be posting spam events every hour.', 'concerned@example.com', 'Concerned User', 'pending', NOW() - INTERVAL '1 day');

-- 4. Meetup Events (from mockIntegrations.ts)
-- Assuming these are for Group '1' for demonstration or linked appropriately
INSERT INTO public.meetup_events (id, "groupId", title, date, time, location, attendees, spots)
VALUES
('1', '1', 'Weekly Game Night - Strategy Games', '2026-01-25', '6:30 PM', 'The Board Room Cafe', 12, 16),
('2', '1', 'Dungeons & Dragons Campaign', '2026-01-28', '7:00 PM', 'Downtown Community Center', 6, 6),
('3', '1', 'Casual Board Game Afternoon', '2026-02-01', '2:00 PM', 'Central Library Meeting Room', 8, 12),
('4', '1', 'Settlers of Catan Tournament', '2026-02-05', '6:00 PM', 'The Board Room Cafe', 15, 16),
('5', '1', 'Party Game Night', '2026-02-08', '7:30 PM', 'Member Host Home', 10, 12);

-- 5. Social Posts (from mockIntegrations.ts)
INSERT INTO public.social_posts (id, "groupId", platform, author, content, timestamp, likes, comments)
VALUES
('1', '1', 'facebook', 'Bay Area Board Gamers', 'Had an amazing turnout last night! 18 people showed up for our strategy game night. Highlights included a 6-player game of Scythe and an intense Wingspan tournament. Thanks everyone!', '2 days ago', 34, 8),
('2', '1', 'facebook', 'Bay Area Board Gamers', 'This Saturday: Bring your favorite party games! We''re planning a casual afternoon session perfect for newcomers. RSVP in the comments 🎲', '4 days ago', 21, 12),
('3', '1', 'facebook', 'Bay Area Board Gamers', 'New to the group? Check out our beginner-friendly game library including Catan, Carcassonne, and Ticket to Ride. All games provided!', '1 week ago', 18, 5);

-- 6. Discord Info (from mockIntegrations.ts)
INSERT INTO public.discord_info (id, "groupId", "serverName", "memberCount", "onlineCount", channels, "recentMessages")
VALUES
('1', '1', 'SF Bay Area Board Gamers', 248, 42, 
 '[{"name": "general-chat", "category": "General"}, {"name": "game-night-planning", "category": "Events"}, {"name": "rules-questions", "category": "Help"}, {"name": "trade-sell", "category": "Marketplace"}]'::jsonb,
 '[{"author": "GameMaster42", "message": "Who''s coming to Friday''s game night?", "timestamp": "2 hours ago"}, {"author": "BoardGameBeth", "message": "I can bring Wingspan and Ticket to Ride!", "timestamp": "1 hour ago"}, {"author": "DiceRoller99", "message": "Count me in! What time?", "timestamp": "45 minutes ago"}]'::jsonb
);
